name: Python Test

on:
  pull_request:
    paths:
    # Only the submission module currently provides unit tests
    - 'scripts/src/submission/*'

jobs:
  enforce:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: ./.github/actions/setup-python
    - name: Set up Python 3.x Part 2
      run: |
        # set up python
        python3 -m venv ve1
        cd scripts
        ../ve1/bin/pip3 install -r requirements.txt
        ../ve1/bin/pip3 install .
        cd ..
    - name: Run pytest
      run: |
        ./ve1/bin/pytest scripts/src/submission/
